### ISSUE TITLE
Variable content as element

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-conformance#1]
@dmj wouldn't we expect `count($foobar) = 1` (or `count($foobar/self::html:p) = 1`) instead to be valid here?
The value of `$foobar` should be the element itself, rather than its (document node?) parent, by my reading. Or have I misunderstood?

https://github.com/Schematron/schematron-conformance/blob/713eae8b50b48c17d0b16fa06aa7b3f9a5d73053/src/main/resources/tests/core/let-value-element-content-01.xml#L17

Thank you again for this suite.

**Comment by dmj** [comment]
I think you are right! I mistakenly assumed the XSLT behavior of a xsl:variable w/o type information to be the right thing to do, i..e. wrap the element node in a document node.
