### ISSUE TITLE
`assert` not in Schematron namespace

### ISSUE THREAD

**Issue by AndrewSales** [Schematron/schematron-conformance#2]
https://github.com/Schematron/schematron-conformance/blob/428f328f54f16679f92d0327ff2cffcb574b7d4a/src/main/resources/tests/core/include-baseuri-fixup-01.xml#L14

I don't think it affects the outcome of the test either way(?), but this element is currently in the test suite (`tag:dmaus@dmaus.name,2019:Schematron:Testsuite`) namespace.

**Comment by dmj** [comment]
Yes, this is a mistake. Fixed!
